<?php

declare (strict_types = 1);

namespace App\Model\Rabc;

use App\Model\Model;

class AdminRole extends Model
{
    protected $primaryKey = 'role_id';

    public function menus()
    {
        return $this->belongsToMany(AdminMenu::class, 'role_with_menus', 'role_id', 'menu_id')
                    ->where(['is_delete' => 0, 'is_check' => 1])
                    ->orderBy('menu_sort', 'ASC');
    }

    public function add(array $params, int $start_filter = 1)
    {
        $role = parent::add($params, $start_filter); // TODO: Change the autogenerated stub;

        // 角色关联菜单
        $this->setRoleMenu($role, $params);

        return $role;
    }

    public function edit($params)
    {
        parent::edit($params); // TODO: Change the autogenerated stub

        // 角色关联菜单
        $this->setRoleMenu($this->find($params[$this->getKeyName()]), $params);

        return true;
    }

    /**
     * 设置关联菜单
     *
     * @param $admin
     * @param $params
     *
     * @return bool
     */
    private function setRoleMenu($role, $params) : bool
    {
        $request_menus = $params['menu_ids'] ?? [];
        $all_menus = empty($request_menus) ? [] : AdminMenu::find($request_menus)->toArray();//当前选中的角色

        $new_all_menus = array_column($all_menus, 'menu_id', 'menu_id');
        $has_menus = $role->menus->toArray(); // 当前已有的菜单权限

        $new_has_menus = array_column($has_menus, 'menu_id', 'menu_id');

        // 管理员与角色关联表
        $roleWithMenu = RoleWithMenu::getInstance();

        /**
         * 添加的菜单
         */
        $add_menus = get_array_diff($new_all_menus, $new_has_menus);
        if ( !empty($add_menus) ) {
            foreach ($add_menus as $menu) {
                $roleWithMenu->add(['role_id' => $role->role_id, 'menu_id' => $menu,]);
            }
        }

        /**
         * 要删除的菜单
         */
        $delete_menus = get_array_diff($new_has_menus, $new_all_menus);
        if ( !empty($delete_menus) ) {
            foreach ($delete_menus as $menu) $roleWithMenu->cnpscyWhere(['role_id' => $role->role_id, 'menu_id' => $menu,])
                                                          ->delete();
        }
        return true;
    }
}