<?php

declare(strict_types=1);

namespace App\Controller\Admin;

use App\Model\Rabc\AdminMenu;
use App\Request\Admin\AdminMenuRequest;
use Hyperf\HttpServer\Contract\RequestInterface;

class AdminMenus extends BaseController
{
    // 设定模型
    protected $model = AdminMenu::class;
    // 验证器
    protected $validator = AdminMenuRequest::class;

    public function index(RequestInterface $request)
    {
        // return parent::index($request); // TODO: Change the autogenerated stub

        $list = $this->modelInstance->getSelectLists();
        foreach ($list as &$v){
            $v['has_child'] = empty($v['_child']) ? false : true;
        }
        return $this->success($list);
    }
}
