<?php

declare(strict_types=1);

namespace App\Controller\Admin;

use App\Model\Log\AdminLoginLog;

class AdminLoginLogs extends BaseController
{
    // 设定模型
    protected $model = AdminLoginLog::class;

    protected function setSearchWhereFilter(&$model, array $params = []) : void
    {
        if ( isset($params['admin_id']) && !empty($params['admin_id']) ) {
            $model->where('admin_id', $params['admin_id']);
        }
        if ( isset($params['is_check']) && !empty($params['is_check']) && $params['is_check'] > -1 ) {
            $model->where('is_check', $params['is_check']);
        }
        parent::setSearchWhereFilter($model, $params); // TODO: Change the autogenerated stub
    }
}
