<?php

declare(strict_types=1);

namespace App\Controller\Admin;

use App\Model\System\Banner;
use App\Request\Admin\BannerRequest;
use Hyperf\Di\Annotation\Inject;

class Banners extends BaseController
{
    // 设定模型
    protected $model = Banner::class;

    /**
     * 验证器
     *
     * @Inject
     * @var BannerRequest
     */
    protected $validator;

    protected function setSearchWhereFilter(&$model, array $params = []) : void
    {
        if ( isset($params['search']) && !empty($params['search']) ) {
            $model->where('banner_name', 'like', "%{$params['search']}%");
        }
        if ( isset($params['is_check']) && !empty($params['is_check']) && $params['is_check'] > -1 ) {
            $model->where('is_check', $params['is_check']);
        }
        parent::setSearchWhereFilter($model, $params); // TODO: Change the autogenerated stub
    }
}
